<a href="https://colab.research.google.com/github/jaisurya93945/AI/blob/main/month1/week1_python_foundations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 – Python Foundations

## Goal:
- Master OOP
- Exception Handling
- Logging
- CSV Handling

## Author:
JAISURYA B

In [1]:
print("github sync test")

github sync test


# WEEK - 1
## DAY -1
## imports basics of NumPy

##Why NumPy is Used

Your idea was correct but incomplete.

Better explanation:

NumPy is used because:

1️⃣ Vectorized operations
2️⃣ Faster than Python loops
3️⃣ Optimized C backend
4️⃣ Handles matrix math easily

In [2]:
import pandas as pd
import logging
import sys

#logging handlers
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    stream=sys.stdout
)

logging.info("Logging initialized successfully.")

2026-05-16 22:49:00,609 [INFO] Logging initialized successfully.


## DatasetLoader Class

In [3]:
class DatasetLoader:
  def __init__(self, filepath):
    self.filepath = filepath
    logging.info(f"Initializing DatasetLoader with filepath: {filepath}")

  def load_data(self):
    try:
      data = pd.read_csv(self.filepath)
      logging.info("File loaded successfully.")
      return data
    except FileNotFoundError:
      logging.error("File not found.")
      return None

  def get_shape(self, data):
    if data is not None:
      logging.info(f"Dataset shape: {data.shape}")
      return data.shape
    else:
      logging.warning("Data is None.")
      return None

In [4]:
loader = DatasetLoader("/content/retail_customer_segmentation.csv")
data = loader.load_data()
loader.get_shape(data)

2026-05-16 22:49:00,626 [INFO] Initializing DatasetLoader with filepath: /content/retail_customer_segmentation.csv
2026-05-16 22:49:00,631 [ERROR] File not found.
2026-05-16 22:49:00,632 [WARNING] Data is None.


# DATA SET SHAPES
## rows and coloumns

##### learning the dataset shape using a realtime dataset in the below code there are 2 rows and 3 coloumns for this it can be imagined as (2,3) that means 2 training examples and 3 features per example

## connect this to ML

##### X.shape = (2,3)

##### 2 samples
##### 3 features



In [5]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


#### Now lets deepen the understanding

In [6]:
arr = np.array([[1,2,3],[4,5,6]])

print("first row:", arr[0])
print("second row:", arr[:,0])

first row: [1 2 3]
second row: [1 4]


##### here first row indexing is great it shows the position 0 which is row one so it prints [1 2 3] but i got confused at row 2 so i remember array index as [row,coloumn] so "arr[:,0]" is [1 4] because ':' means all rows and 0 means coloumns so in all rows 0th positioned value which is 1,4

## TASK

##### arr[:,1] = 2 5
##### arr[1,2] = 6
##### arr[1,1] = 5
##### arr[0,0] = 1
##### arr[0,1] = 2
##### arr[1,2] = 5

In [7]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr[1:, 1])
print(arr[:2,2])
print(arr [1:, 1])

[50 80]
[30 60]
[50 80]


##### here we can see different methods of indexing

##### for 1: means positioning from 1 to possible
##### for :2 means before possible except 2 so 1,0 indexing

# BROADCASTING

In [8]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a+b)

[11 22 33]


##### it hase same dimensions (3,) NumPy supports vectorized operations so when we do a+b it will add element by element

##### which is
##### 1 + 10
##### 2 + 20
##### 3 + 30

## NumPy is not Python Lists.

## python concatinates



In [9]:
a = np.array([1,2,3])
b = 10

print(a + b)

[11 12 13]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([20,30])
print(b.shape)

#print(a+b)

#a + b will be error because shape vectorization value error


(2, 3)
(2,)


In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([20,30,40])
print(b.shape)
print(a+b)
#a + b will work cuz from right shape is correct

(2, 3)
(3,)
[[21 32 43]
 [24 35 46]]


## DAY - 2
### Matrix Multiplication and Dot product and ML Prediction Formula

## Dot Product

### example

#### prediction = w1*x1 + w2*x2 + w3*x3

In [12]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1,2,3])

print("Vector a:", a)
print("Vector b:", b)

result = a @ b

print("Dot product:", result)

Vector a: [1 2 3]
Vector b: [1 2 3]
Dot product: 14


## what it means

### [1,2,3] • [1,2,3]

###

### Calculation:

#### 1×1 + 2×2 + 3×3
#### = 1 + 4 + 9
#### = 14 #which is output

In [13]:
weights = np.array([2,3,4])
features = np.array([1,2,3])

prediction = weights @ features

print("Prediction:", prediction,"shapes are:",weights.shape,features.shape)

Prediction: 20 shapes are: (3,) (3,)


In [14]:
weights = np.array([[2,3,4],[5,6,7]])
features = np.array([1,2,3])

prediction = weights @ features
print("shapes are:",weights.shape,features.shape)
print("Prediction:", prediction)

shapes are: (2, 3) (3,)
Prediction: [20 38]


## Matrix Multiplication

### Matrix Multiplication Rule

#### (m × n) @ (n × p) = (m × p)

In [15]:
X = np.array([[1,2,3],
              [4,5,6]])

W = np.array([[1],[2],[3]])

print("X shape:", X.shape)
print("W shape:", W.shape)

y = X @ W

print("Predictions:")
print(y)

X shape: (2, 3)
W shape: (3, 1)
Predictions:
[[14]
 [32]]


## Quick example real life ML

### feature will be

Area,
Bedrooms,
LocationScore.

### Weights learned by model

W = [price_factor1,
     price_factor2,
     price_factor3]

price = Area*w1 + Bedrooms*w2 + Location*w3

## that's exactly

features @ weights

In [16]:
import numpy as np

# dataset (3 samples, 2 features)
X = np.array([[1,2],[3,4],[5,6]])

# weights
W = np.array([[2],[3]])

y = X @ W

print("Predictions:")
print(y, y.shape)

Predictions:
[[ 8]
 [18]
 [28]] (3, 1)


# ============================================
# 🤖 Introduction to Generative AI
# ============================================

"""
🧠 What is Generative AI?

Generative AI is a type of Artificial Intelligence
that can CREATE new content instead of just analyzing data.

It can generate:
✨ Text
🎨 Images
🎵 Music
💻 Code
🎥 Videos

------------------------------------------------

🔥 Real World Examples

💬 ChatGPT  → Generates human-like text
🌌 Gemini   → AI assistant by Google
🎨 DALL·E   → Creates AI images
🎵 Suno     → Generates music
💻 GitHub Copilot → Writes code

------------------------------------------------

⚡ How Does It Work?

Generative AI learns patterns from huge amounts of data.
Then it uses those patterns to generate new outputs.

Example:
If trained on millions of conversations,
it learns how humans talk and respond.

------------------------------------------------

🚀 Why It Matters

Generative AI is transforming:
🏥 Healthcare
🎓 Education
💼 Business
🔐 Cybersecurity
🎮 Gaming
🎬 Content Creation

------------------------------------------------

🎯 My Goal

Learning Generative AI to build:
✅ AI tools
✅ AI-powered platforms
✅ AI Security systems
✅ Intelligent assistants

#Day2 🚀

# ============================================
# 🧠 What is an LLM?
# ============================================

"""
LLM = Large Language Model

An LLM is a powerful AI model trained on MASSIVE amounts of text data.

It understands:
📖 Language
💬 Conversations
🧩 Context
✍️ Prompts
💡 Human-like responses

------------------------------------------------

🔥 Popular LLMs

🤖 GPT
🌌 Gemini
🦙 Llama
🧠 Claude

------------------------------------------------

⚡ What Can LLMs Do?

✅ Answer questions
✅ Generate code
✅ Summarize text
✅ Translate languages
✅ Create content
✅ Help in learning

------------------------------------------------

🛠️ Simple Example

Prompt:
"Write a motivational quote"

LLM Output:
"Small progress every day becomes big success someday."

------------------------------------------------

🚀 Future Use

LLMs are becoming the brain behind:
🔐 AI Security tools
🤖 AI Agents
📚 AI Tutors
💻 Coding assistants
📊 Data analysis systems

#AI #LLM #GenerativeAI