<a href="https://colab.research.google.com/github/jaisurya93945/AI/blob/main/month1/week1_python_foundations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 – Python Foundations

## Goal:
- Master OOP
- Exception Handling
- Logging
- CSV Handling

## Author:
JAISURYA B

In [24]:
print("github sync test")

github sync test


# WEEK - 1
## imports

In [25]:
import pandas as pd
import logging
import sys

#logging handlers
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    stream=sys.stdout
)

logging.info("Logging initialized successfully.")

2026-03-04 12:44:30,990 [INFO] Logging initialized successfully.


## DatasetLoader Class

In [26]:
class DatasetLoader:
  def __init__(self, filepath):
    self.filepath = filepath
    logging.info(f"Initializing DatasetLoader with filepath: {filepath}")

  def load_data(self):
    try:
      data = pd.read_csv(self.filepath)
      logging.info("File loaded successfully.")
      return data
    except FileNotFoundError:
      logging.error("File not found.")
      return None

  def get_shape(self, data):
    if data is not None:
      logging.info(f"Dataset shape: {data.shape}")
      return data.shape
    else:
      logging.warning("Data is None.")
      return None

In [27]:
loader = DatasetLoader("/content/retail_customer_segmentation.csv")
data = loader.load_data()
loader.get_shape(data)

2026-03-04 12:44:31,010 [INFO] Initializing DatasetLoader with filepath: /content/retail_customer_segmentation.csv
2026-03-04 12:44:31,011 [ERROR] File not found.
2026-03-04 12:44:31,013 [WARNING] Data is None.


# DATA SET SHAPES
## rows and coloumns

##### learning the dataset shape using a realtime dataset in the below code there are 2 rows and 3 coloumns for this it can be imagined as (2,3) that means 2 training examples and 3 features per example

## connect this to ML

##### X.shape = (2,3)

##### 2 samples
##### 3 features



In [28]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


#### Now lets deepen the understanding

In [29]:
arr = np.array([[1,2,3],[4,5,6]])

print("first row:", arr[0])
print("second row:", arr[:,0])

first row: [1 2 3]
second row: [1 4]


##### here first row indexing is great it shows the position 0 which is row one so it prints [1 2 3] but i got confused at row 2 so i remember array index as [row,coloumn] so "arr[:,0]" is [1 4] because ':' means all rows and 0 means coloumns so in all rows 0th positioned value which is 1,4

## TASK

##### arr[:,1] = 2 5
##### arr[1,2] = 6
##### arr[1,1] = 5
##### arr[0,0] = 1
##### arr[0,1] = 2
##### arr[1,2] = 5

In [30]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr[1:, 1])
print(arr[:2,2])
print(arr [1:, 1])

[50 80]
[30 60]
[50 80]


##### here we can see different methods of indexing

##### for 1: means positioning from 1 to possible
##### for :2 means before possible except 2 so 1,0 indexing

# BROADCASTING

In [21]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a+b)

[11 22 33]


##### it hase same dimensions (3,) NumPy supports vectorized operations so when we do a+b it will add element by element

##### which is
##### 1 + 10
##### 2 + 20
##### 3 + 30

## NumPy is not Python Lists.

## python concatinates



In [31]:
a = np.array([1,2,3])
b = 10

print(a + b)

[11 12 13]


In [35]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([20,30])
print(b.shape)

#print(a+b)

#a + b will be error because shape vectorization value error


(2, 3)
(2,)


In [33]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([20,30,40])
print(b.shape)
print(a+b)
#a + b will work cuz from right shape is correct

(2, 3)
(3,)
[[21 32 43]
 [24 35 46]]


## DAY - 2
### Matrix Multiplication and Dot product